grass: Version bump. For now readline in DEPENDS is commented out because for some
reason we compile readline --without-curses resulting in these type of failures;

/lib/libreadline.so: undefined reference to `PC'
/lib/libreadline.so: undefined reference to `tgetflag'
/lib/libreadline.so: undefined reference to `tgetent'
/lib/libreadline.so: undefined reference to `UP'
/lib/libreadline.so: undefined reference to `tputs'
/lib/libreadline.so: undefined reference to `tgoto'
/lib/libreadline.so: undefined reference to `tgetnum'
/lib/libreadline.so: undefined reference to `BC'
/lib/libreadline.so: undefined reference to `tgetstr'

Does anyone with a better memory than I remember why we omit ncurses from
readline?