python2-numpy: Dropping this back to 1.16.4 else you will get;
+ CC="gcc"
+ CXX="g++"
+ CPP="cpp"
+ CFLAGS=" -O2 -march=x86-64 -pipe"
+ CXXFLAGS=" -O2 -march=x86-64 -pipe"
+ CPPFLAGS=" -D_FORTIFY_SOURCE=2"
+ LDFLAGS=" -s"
+ MAKES="9"
+ Enabled wrapper script usage
+ running "default_python2_build"
Traceback (most recent call last):
File "setup.py", line 31, in <module>
raise RuntimeError("Python version >= 3.5 required.")
RuntimeError: Python version >= 3.5 required.

Seems 1.17.0 cannot be built with python2.