Revert "gtk+-2: updated to 2.24.0"
This reverts commit 09e0f518e89d991b04144d8a71a302d7a7da2f61.

Breaks compilation of evolution-data-server 2.32.2

e-name-selector-dialog.c: In function 'e_name_selector_dialog_populate_categories':
e-name-selector-dialog.c:119:3: error: implicit declaration of function 'gtk_combo_box_append_text'