gdal: Adding a BUILD so the install does not fail with this;
+ Installing default documentation to: /usr/share/doc/gdal/NEWS
ERROR: Package installs files in incorrect locations!
/usr/etc
/usr/etc/bash_completion.d
/usr/etc/bash_completion.d/gdal-bash-completion.sh
ERROR: problems running POST_BUILD plugins!