perl-tk: Adjusting the BUILD to fix a failure on Xlib.h conflicts. Used the fix
from http://lists.suse.com/archive/opensuse-commit/2010-11/msg00719.html

The specific failure:
In file included from Xlib_f.c:8:0:
Xlib.h:22:15: error: conflicting types for 'XKeycodeToKeysym'
/usr/include/X11/Xlib.h:1694:15: note: previous declaration of 'XKeycodeToKeysym' was here
make[1]: *** [Xlib_f.o] Error 1
make[1]: Leaving directory `/usr/src/Tk-804.029/pTk'
make: *** [pTk/libpTk.a] Error 2