Revert "phonon: version bumped to 4.6.0."
This reverts commit 8e2957807c9619203416776974f810dce6f2cfd0.

This will break phonon-backend-vlc and phonon-backend-gstreamer with this;

[  0%] Built target phonon_vlc_automoc
Scanning dependencies of target phonon_vlc
[  6%] Building CXX object vlc/CMakeFiles/phonon_vlc.dir/phonon_vlc_automoc.cpp.o
In file included from /usr/src/phonon-backend-vlc-0.4.1/phonon-backend-vlc-oosb/vlc/moc_devicemanager.cpp:10:0,
                 from /usr/src/phonon-backend-vlc-0.4.1/phonon-backend-vlc-oosb/vlc/phonon_vlc_automoc.cpp:10:
/usr/src/phonon-backend-vlc-0.4.1/phonon-backend-vlc-oosb/vlc/../../vlc/devicemanager.h:26:36: fatal error: Phonon/ObjectDescription: No such file or directory
compilation terminated.
make[2]: *** [vlc/CMakeFiles/phonon_vlc.dir/phonon_vlc_automoc.cpp.o] Error 1
make[1]: *** [vlc/CMakeFiles/phonon_vlc.dir/all] Error 2
make: *** [all] Error 2