heimdal: On a fresh install heimdal was tanking with;
  CCLD     verify_krb5_conf
/usr/bin/ld: ./.libs/libkrb5.so: undefined reference to `_krb5_pk_kx_confirm'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1938: verify_krb5_conf] Error 1

Seems to be related to; https://github.com/heimdal/heimdal/issues/106

Making --enable-pk-init a default switch in BUILD fixes the problem.