llvm: Adding BPF to targets. A bump of v4l-utils would fail with;
Making all in bpf_protocols
make[4]: Entering directory '/usr/src/v4l-utils-1.16.1/utils/keytable/bpf_protocols'
clang -idirafter /usr/lib/clang/6.0.1/include -idirafter /usr/include -I../../../include -target bpf -O2 -c grundig.c
error: unable to create target: 'No available targets are compatible with this triple.'
1 error generated.