This is a oneliner sedit that fixes libidn so that it *does not* cause kdenetwork3 make to croak on;
/libiris_xmpp_core_la-tlshandler.Tpo"; exit 1; fi
In file included from /usr/include/stringprep.h:32,
                 from jid.cpp:24:
/usr/include/idn-int.h:47:26: error: no include path in which to search for stdint.h

This BUILD should be revisited when libidn is once again
bumped and does not cause kdenetwork3 breakage.



git-svn-id: svn+ssh://foo-projects.org/var/svn/lunar/moonbase/trunk@25631 fe636330-a7f5-0310-8408-fdd8893149bb