php5: Ran into an odd situtation. lin postgresql when done will recompile php5 if installed.
Php5 tanked with;

 /usr/bin/ld: ext/gd/.libs/gd.o: undefined reference to symbol 'XpmLibraryVersion'
 /usr/lib64/libXpm.so.4: error adding symbols: DSO missing from command line

So from cli did a lin -c php5, compiled fine. Did another lin postgresql, again php5
tanked with the same error. Adding libXpm to DEPENDS fixes this.

Don't know what to make of that.