Revert "bluedevil: version bumped to 1.2."
This reverts commit 1914d7fe8182546c18e8040375b8d970c89a55b5.

Don't know how you got around this problem;

[ 29%] Building CXX object src/daemon/kded/CMakeFiles/kded_bluedevil.dir/kded_bluedevil_automoc.o
[ 29%] Building CXX object src/daemon/kded/CMakeFiles/kded_bluedevil.dir/BlueDevilDaemon.o
/usr/src/bluedevil-1.2/src/daemon/kded/BlueDevilDaemon.cpp: In member function 'QMapDeviceInfo BlueDevilDaemon::knownDevices()':
/usr/src/bluedevil-1.2/src/daemon/kded/BlueDevilDaemon.cpp:140:44: error: 'class BlueDevil::Adapter' has no member named 'startStableDiscovery'
make[2]: *** [src/daemon/kded/CMakeFiles/kded_bluedevil.dir/BlueDevilDaemon.o] Error 1
make[1]: *** [src/daemon/kded/CMakeFiles/kded_bluedevil.dir/all] Error 2
make: *** [all] Error 2

bluedevil-1.2 will only compile with the current git version of libbluedevil which will be version 1.9 and it isn't
out yet; also its why I didn't bump bluedevil.