xfce4-panel: depend on libxfcegui4 instead of libxfce4util
Otherwise, get compilation error:

checking for libxfcegui4-1.0 >= 4.6.0... not found
*** The required package libxfcegui4-1.0 was not found on your system.

libxfcegui4 already depends on libxfce4util.