jemalloc：'__throw_bad_alloc' is not a member of 'std'
g++ -std=c++17 -Wall -Wextra -g3 -fvisibility=hidden -Wimplicit-fallthrough -Wdeprecated-declarations -O3 -O2 -march=x86-64 -fno-plt -fexceptions -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-clash-protection -fPIC -DPIC -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -o src/jemalloc_cpp.pic.o src/jemalloc_cpp.cpp
src/jemalloc_cpp.cpp: In function 'void* handleOOM(std::size_t, bool)':
src/jemalloc_cpp.cpp:103:22: error: '__throw_bad_alloc' is not a member of 'std'; did you mean '__throw_bad_cast'?
  103 |                 std::__throw_bad_alloc();
      |                      ^~~~~~~~~~~~~~~~~
      |                      __throw_bad_cast
make: *** [Makefile:533: src/jemalloc_cpp.pic.o] Error 1