firefox: Bump to 32. Compiled with shared-js so that can be re-enabled from mozconfig.
Don't need the BUILD sedit, in fact it was causing me a;

        package-manifest ../../dist ../../dist/firefox \

  File "/usr/src/mozilla-release/toolkit/mozapps/installer/packager.py", line 379
    buildconfig.substs['MOZ_DISABLE_STARTUPCACHE'] != '1':
                                                         ^
SyntaxError: invalid syntax
/usr/src/mozilla-release/toolkit/mozapps/installer/packager.mk:714: recipe for target 'stage-package' failed
make[1]: *** [stage-package] Error 1
make[1]: Leaving directory '/usr/src/mozilla-release/build-mozilla/browser/installer'
/usr/src/mozilla-release/browser/build.mk:21: recipe for target 'install' failed
make: *** [install] Error 2