gobject-introspection: I don't think we need this BUILD anymore. Those sedits
cause the build to fail on;

  GISCAN GLib-2.0.gir
Traceback (most recent call last):
  File "../tools/g-ir-scanner", line 43, in <module>
    from giscanner.scannermain import scanner_main
  File "/usr/src/gobject-introspection-0.9.12/giscanner/scannermain.py", line 34, in <module>
    from giscanner.dumper import compile_introspection_binary
  File "/usr/src/gobject-introspection-0.9.12/giscanner/dumper.py", line 26, in <module>
    from .gdumpparser import IntrospectionBinary
  File "/usr/src/gobject-introspection-0.9.12/giscanner/gdumpparser.py", line 30, in <module>
    from .transformer import TransformerException
  File "/usr/src/gobject-introspection-0.9.12/giscanner/transformer.py", line 28, in <module>
    from .girparser import GIRParser
  File "/usr/src/gobject-introspection-0.9.12/giscanner/girparser.py", line 26, in <module>
    from .girwriter import COMPATIBLE_GIR_VERSION
  File "/usr/src/gobject-introspection-0.9.12/giscanner/girwriter.py", line 25, in <module>
    from .xmlwriter import XMLWriter
  File "/usr/src/gobject-introspection-0.9.12/giscanner/xmlwriter.py", line 70, in <module>
    with LibtoolImporter(None,None)(None, None):
TypeError: 'LibtoolImporter' object is not callable
make[2]: *** [GLib-2.0.gir] Error 1
make[2]: Leaving directory `/usr/src/gobject-introspection-0.9.12/gir'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/src/gobject-introspection-0.9.12'
make: *** [all] Error 2